// This file is auto-generated by @hey-api/openapi-ts

// region struct
export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  id: number
  name: string | null
  role: string | null
  status: number
  supervisor_id?: number | null
  password: string
}

export type UserPublic = {
  id: number
  name: string | null
  role: string | null
  status: number
  supervisor_id?: number | null
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserQuery = {
  name?: string | null
  role?: string | null
  status?: number | null
  skip?: number | null
  limit?: number | null
}

export type UserUpdate = {
  id: number
  name?: string | null
  role?: string | null
  status?: number | null
  supervisor_id?: number | null
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic
// endregion

// region FastAPI User
export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message
// endregion

// region Castor User
export type QueryUsersData = {
  requestBody: UserQuery
}

export type QueryUsersResponse = {
  data: Array<UserPublic>
  count: number
}

export type QueryUserSelfResponse = UserPublic

export type CreateUserData = {
  requestBody: UserCreate
}

export type CreateUserResponse = UserPublic

export type UpdateUserData = {
  requestBody: UserUpdate
}

export type UpdateUserResponse = UserPublic

// endregion

// region product
export type ProductPublic = {
  code: string,
  name: string,
  broker: string,
  broker_name: string,
  is_sub: number,
  created_at: Date,
  updated_at: Date,
  parent_code?: number,
}

export type ProductQuery = {
  code?: string | null,
  name?: string | null,
  broker?: string | null,
  broker_list?: Array<string> | null,
  type_list?: Array<string> | null
  skip?: number | null
  limit?: number | null
  sort_field?: string | null
  sort_order?: string | null
}

export type QueryProductsData = {
  requestBody: ProductQuery
}

export type QueryProductsResponse = {
  data: Array<ProductPublic>
  count: number
}

export type QueryProductDictResponse = {
  data: Map<string, Array<ProductPublic>>,
}

export type LiveProduct = {
  code?: string | null,
  name?: string | null,
  date?: string | null,
  total_share?: string | null,
  total_nav?: string | null,
}

export type StrategyNav = {
  strategy?: string | null,
  total_nav: string,
}

export type QueryLiveProductListResponse = {
  product_list: Array<LiveProduct>,
  strategy_list: Array<StrategyNav>,
}
// endregion

// region product info
export type QueryProductInfoBoardResponse = {
  code?: string | null,
  name: string | null,
  broker_name?: string | null,
  index_name?: string | null,
  create_date?: string | null,
  entry_date?: string | null,
  curr_date?: string | null,
  status?: string | null,
  unit_nav?: string | null,
  cum_nav?: string | null,
  live_days?: number | null,
  total_rof?: string | null,
  year_rof?: string | null,
  total_arof?: string | null,
  max_drawdown?: string | null,
  monthly_volatility?: string | null,
  annual_volatility?: string | null,
  sharp?: string | null,
  excess_total_rof?: string | null,
  excess_total_arof?: string | null,
}

export type ProductInfo = {
  code: string | null,
  name: string | null,
  broker?: string | null,
  broker_name?: string | null,
  share_class?: string | null,
  strategy?: string | null,
  description?: string | null,
  index_name?: string | null,
  index_code?: string | null,
  create_date?: number | null,
  entry_date?: number | null,
  filing_date?: number | null,
  status?: string | null,
  status_code?: number | null,
  is_segregated_account?: number | null,
  manage_fee?: number | null,
  performance_fee?: number | null,
  buy_fee?: number | null,
  fund_manager?: string | null,
  risk_level?: string | null,
  curr_date?: number | null,
  last_week_trading_day?: number | null,
  last_month_trading_day?: number | null,
  last_quarter_trading_day?: number | null,
  last_year_trading_day?: number | null,
}

export type ProductInfoQuery = {
  code?: string | null,
}

export type QueryProductInfoData = {
  requestBody: ProductInfoQuery
}
export type QueryProductInfoResponse = ProductInfo
export type UpdateProductInfoData = {
  requestBody: ProductInfo
}
export type UpdateProductInfoResponse = ProductInfo
// endregion

// region product report
export type ProductReportQuery = {
  code?: string | null,
  period?: string | null,
  start_date?: number | null,
  end_date?: number | null,
  template_id?: number | null,
}

export type QueryProductReportData = {
  requestBody: ProductReportQuery
}

export type QueryProductReportResponse = {
  code?: string | null,
  name: string | null,
  broker_name?: string | null,
  index_name?: string | null,
  strategy?: string | null,
  description?: string | null,
  create_date?: string | null,
  entry_date?: string | null,
  status?: string | null,
  period?: string | null,
  curr_date?: string | null,
  live_days?: number | null,
  unit_nav?: string | null,
  cum_nav?: string | null,
  total_rof?: string | null,
  ytd_rof?: string | null,
  total_arof?: string | null,
  mdd?: string | null,
  daily_volatility?: string | null,
  weekly_volatility?: string | null,
  annual_volatility?: string | null,
  excess_annual_volatility?: string | null,
  excess_sharp?: string | null,
  excess_mdd?: string | null,
  sharp?: string | null,
  index_rof?: string | null,
  excess_total_rof?: string | null,
  excess_total_arof?: string | null,
  nav_list?: Array<string> | null,
  date_list?: Array<string> | null,
  total_nav_rof_list?: Array<string> | null,
  total_index_rof_list?: Array<string> | null,
  total_excess_list?: Array<string> | null,
  month_data_map?: Map<string, Array<string>> | null,
  main_index_data?: Map<string, any> | null,
  week_rof?: string | null,
  index_week_rof?: string | null,
  week_excess?: string | null,
  ytd_excess?: string | null,
  total_excess?: string | null,
  total_aexcess?: string | null,
  index?: string | null,
  report_tpl?: ProductReportTpl | null,
}

export type ProductReport = QueryProductReportResponse
// endregion

// region mul-product report cfg

// 产品报告配置
export type ProductReportCfg = {
  code?: string | null,
  name: string,
  is_display: number,
  start_date?: number | null,
  template_id?: number | null,
  index_name?: number | null,
  create_date?: number | null,
  entry_date?: number | null,
}

// 查询单产品的报告配置
export type ProductReportCfgByCodeQuery = {
  code?: string | null,
}
export type QueryProductCfgByCodeData = {
  requestBody: ProductReportCfgByCodeQuery
}
export type QueryProductReportCfgByCodeResponse = ProductReportCfg

// 更新单产品的报告配置
export type UpdateProductReportCfgData = {
  requestBody: ProductReportCfg
}
export type UpdateProductReportCfgResponse = ProductReportCfg

// 查询所有产品的报告配置
export type QueryProductReportCfgListResponse = {
  cfg_list: Array<ProductReportCfg>
}

// 查询并生成多产品周报
export type QueryMulProductReport = {
  end_date?: number | null,
}
export type QueryMulProductReportData = {
  requestBody: QueryMulProductReport
}

// 多产品周报的每个产品的报告元素
export type MulProductReport = {
  code: string,
  name?: string | null,
  index_name?: string | null,
  create_date?: string | null,
  entry_date?: string | null,
  unit_nav?: string | null,
  cum_nav?: string | null,
  sharp?: string | null,
  mdd?: string | null,
  weekly_volatility?: string | null,
  annual_volatility?: string | null,
  week_rof?: string | null,
  ytd_rof?: string | null,
  total_rof?: string | null,
  total_arof?: string | null,
  week_excess?: string | null,
  ytd_excess?: string | null,
  total_excess?: string | null,
  total_aexcess?: string | null,
  excess_mdd?: string | null,
  excess_sharp?: string | null,
  excess_annual_volatility?: string | null,
  date_list?: Array<string> | null,
  nav_list?: Array<string> | null,
  week_nav_rof_list?: Array<string> | null,
  week_excess_list?: Array<string> | null,
  week_index_rof_list?: Array<string> | null,
}

export type QueryMulProductReportResponse = {
  report_list: Array<MulProductReport>,
}

// 产品报告配置模板
export type ProductReportTpl = {
  id: number,
  name?: string | null,
  show_create_date?: number | null,
  show_entry_date?: number | null,
  show_unit_nav?: number | null,
  show_cum_nav?: number | null,
  show_sharp?: number | null,
  show_mdd?: number | null,
  show_week_volatility?: number | null,
  show_avolatility?: number | null,
  show_week_rof?: number | null,
  show_ytd_rof?: number | null,
  show_total_rof?: number | null,
  show_total_arof?: number | null,
  show_week_excess?: number | null,
  show_ytd_excess?: number | null,
  show_total_excess?: number | null,
  show_total_aexcess?: number | null,
  show_excess_mdd?: number | null,
  show_excess_sharp?: number | null,
  show_excess_avolatility?: number | null,
  show_index_rof?: number | null,
}

export type QueryProductReportTplListResponse = {
  tpl_list: Array<ProductReportTpl>,
}

export type AddProductReportTplData = {
  requestBody: ProductReportTpl
}
export type UpdateProductReportTplData = {
  requestBody: ProductReportTpl
}


export type DeleteProductReportTpl = {
  tpl_id: number,
}
export type DeleteProductReportTplData = {
  requestBody: DeleteProductReportTpl
}
// endregion

// region home
export type AumDetail = {
  code: string,
  name: string,
  date: string,
  total_nav: string,
}

export type QueryAumResponse = {
  aum: string,
  res_list: Array<AumDetail>,
}

export type QueryOpenDayByCode = {
  code?: string | null,
}

export type OpenDay = {
  code: string,
  is_week_x?: number | null,
  is_week_1?: number | null,
  is_week_2?: number | null,
  is_week_3?: number | null,
  is_week_4?: number | null,
  is_week_5?: number | null,
  is_week_last_day?: number | null,
  is_month_x_last_day?: number | null,
  is_month_6_last_day?: number | null,
  is_month_12_last_day?: number | null,
}

export type QueryOpenDayByCodeResponse = OpenDay

export type UpdateOpenDayData = {
  requestBody: OpenDay
}

export type OpenDayCalendarDate = {
  date: string,
  day: number,
  weekday: number,
  is_trading_day: boolean,
  open_product_list: Array<string>,
}

export type QueryOpenDayCalendarResponse = {
  year: number
  month: number
  cal_dict: Array<OpenDayCalendarDate>
}

export type QueryAccrualDayByCode = {
  code?: string | null,
}

export type AccrualDay = {
  code: string,
  is_month_6_last_day?: number | null,
  is_month_12_last_day?: number | null,
  is_xxxx1201?: number | null,
  is_xxxx1231?: number | null,
  is_xxxx0630?: number | null,
}

export type QueryAccrualDayByCodeResponse = AccrualDay

export type UpdateAccrualDayData = {
  requestBody: AccrualDay
}

export type AccrualDayCalendarDate = {
  date: string,
  day: number,
  weekday: number,
  is_trading_day: boolean,
  accrual_product_list: Array<string>,
}

export type QueryAccrualDayCalendarResponse = {
  year: number
  month: number
  cal_dict: Array<AccrualDayCalendarDate>
}
// endregion

// region product account
export type QueryProductAccountByCode = {
  code?: string | null,
}

export type ProductAccount = {
  code: string,
  sales: string,
  amount?: number | null,
  account_type: string,
  account: string,
  broker?: string | null,
  office?: string | null,
  fee?: string | null,
  status: number,
}

export type QueryProductAccountByCodeResponse = {
  acct_list: Array<ProductAccount>,
}

export type AddProductAccountData = {
  requestBody: ProductAccount,
}

export type UpdateProductAccountData = {
  requestBody: ProductAccount,
}

export type DeleteProductAccount = {
  code: string,
  account: string,
}

export type DeleteProductAccountData = {
  requestBody: DeleteProductAccount,
}
// endregion

// region product init
export type ProductInit = {
  id?: number | null,
  product_name?: string | null,
  strategy?: string | null,
  broker_name?: string | null,
  cust_info?: string | null,
  is_segregated_account?: number | null,
  open_day?: string | null,
  share_class?: string | null,
  manage_fee?: string | null,
  performance_fee?: string | null,
  buy_fee?: string | null,
  comment?: string | null,

  is_init_data_ok?: number | null,
  is_init_data_review?: number | null,
  is_init_element?: number | null,
  is_init_contract?: number | null,
  is_customer_buy?: number | null,
  is_filing?: number | null,
  is_entry?: number | null,
}

export type AddProductInitData = {
  requestBody: ProductInit,
}

export type UpdateProductInitData = {
  requestBody: ProductInit,
}
export type DeleteProductInit = {
  init_id?: number | null,
}

export type DeleteProductInitData = {
  requestBody: DeleteProductInit,
}

export type QueryProductInitListResponse = {
  init_list: Array<ProductInit>,
}
// endregion

// region product dashboard
export type ProductDashBoard = {
  code?: string | null,
  name?: string | null,
  share_class?: string | null,
  status?: string | null,
  create_date?: string | null,
  filing_date?: string | null,
  entry_date?: string | null,
  broker_name?: string | null,
  strategy?: string | null,
  is_segregated_account?: string | null,
  open_day?: string | null,
  manage_fee?: string | null,
  performance_fee?: string | null,
  buy_fee?: string | null,
  // sell_fee?: string | null,
  accrual_day?: string | null,
  fund_manager?: string | null,
  risk_level?: string | null,
}

export type QueryDashboardResponse = {
  dash_list: Array<Array<ProductDashBoard>>
}
// endregion

// region product value
export type ProductValuePublic = {
  code: string,
  name: string,
  broker: string,
  broker_name: string,
  date: number,
  unit_nav?: string | null,
  cum_nav?: string | null,
  total_nav?: string | null,
  total_share?: string | null,
}

export type ProductValueQuery = {
  code?: string | null,
  name?: string | null,
  broker?: string | null,
  broker_list?: Array<string> | null,
  start_date?: string | null, // "20240401"
  end_date?: string | null,   // "20240413"
  skip?: number | null,
  limit?: number | null,
  sort_field?: string | null,
  sort_order?: string | null,
}

export type QueryProductsValueData = {
  requestBody: ProductValueQuery
}

export type QueryProductsValueResponse = {
  data: Array<ProductValuePublic>,
  count: number
}
// endregion

// region customer trade
export type CustomerTrade = {
  id?: number | null,

  product_code?: string | null,
  product_name?: string | null,
  certi_type?: string | null,
  certi_no?: string | null,
  trade_type?: string | null,
  open_date?: string | null,
  sales?: string | null,
  cust_name?: string | null,
  cust_type?: string | null,
  is_new_customer?: number | null,
  ams_comment?: string | null,
  ams_step?: string | null,
  ams_status?: string | null,
  amount?: number | null,
  share?: number | null,
  trade_account?: string | null,
}

export type AddCustomerTradeData = {
  requestBody: CustomerTrade,
}

export type DelCustomerTrade = {
  trade_id?: number | null,
}

export type DelCustomerTradeData = {
  requestBody: DelCustomerTrade
}

export type UpdateCustomerTradeData = {
  requestBody: CustomerTrade,
}

export type QueryCustomerTradeListResponse = {
  trade_list: Array<CustomerTrade>,
}

export type CustomerPosition = {
  fund_acct?: string | null,
  trade_acct?: string | null,
  bank_acct?: string | null,
  broker_name?: string | null,
  product_code?: string | null,
  product_name?: string | null,
  date?: string | null,
  share: string,
  nav: string,
}

export type CustomerInfo = {
  cust_name?: string | null,
  cust_type?: string | null,
  certi_type?: string | null,
  certi_no?: string | null,
  sum_nav?: string | null,
  is_protect?: number | null,
  pos_list?: Array<CustomerPosition>,
  fund_acct?: string | null,
  trade_acct?: string | null,
  bank_acct?: string | null,
  broker_name?: string | null,
}

export type CustomerInfoQuery = {
  cust_name?: string | null,
  product_name?: string | null,
  certi_no?: string | null,
  skip?: number | null,
  limit?: number | null,
}

export type CustomerInfoQueryData = {
  requestBody: CustomerInfoQuery,
}

export type CustomerInfoQueryResponse = {
  info_list: Array<CustomerInfo>,
  count: number | null,
}

export type UpdateCustomerInfoData = {
  requestBody: CustomerInfo,
}

// endregion

export type DingTalkAtSomeone = {
  title: string,
  msg: string,
  to_list: Array<string>
}

export type DingTalkAtSomeoneData = {
  requestBody: DingTalkAtSomeone,
}